exclude:
    - 'vendor/**'
    - '_hacks.scss'
linters:
    Comment:
        enabled: false
    DeclarationOrder:
        enabled: false
    Indentation:
        width: 4
        allow_non_nested_indentation: true
    LeadingZero:
        style: include_zero
    MergeableSelector:
        enabled: false
    PlaceholderInExtend:
        enabled: false
    PropertySortOrder:
        order:
            - content
            - position
            - top
            - bottom
            - left
            - right
            - z-index
            - overflow
            - overflow-x
            - overflow-y
            - float
            - clear
            - display
            - table-layout
            - empty-cells
            - vertical-align
            - box-sizing
            - width
            - max-width
            - min-width
            - height
            - max-height
            - min-height
            - border
            - border-top
            - border-bottom
            - border-left
            - border-right
            - border-width
            - border-top-width
            - border-bottom-width
            - border-left-width
            - border-right-width
            - border-style
            - border-top-style
            - border-bottom-style
            - border-left-style
            - border-right-style
            - border-color
            - border-top-color
            - border-bottom-color
            - border-left-color
            - border-right-color
            - border-radius
            - border-top-left-radius
            - border-top-right-radius
            - border-bottom-left-radius
            - border-bottom-right-radius
            - border-collapse
            - border-spacing
            - outline
            - outline-width
            - outline-style
            - outline-color
            - margin
            - margin-top
            - margin-bottom
            - margin-left
            - margin-right
            - padding
            - padding-top
            - padding-bottom
            - padding-left
            - padding-right
            - list-style
            - list-style-type
            - list-style-image
            - list-style-position
            - counter-increment
            - counter-reset
            - font
            - font-family
            - font-size
            - font-weight
            - font-style
            - font-variant
            - font-size-adjust
            - font-stretch
            - direction
            - letter-spacing
            - word-spacing
            - white-space
            - quotes
            - orphans
            - widows
            - line-height
            - text-align
            - text-decoration
            - text-indent
            - text-justify
            - text-overflow
            - text-shadow
            - text-transform
            - color
            - background
            - background-color
            - background-image
            - background-repeat
            - background-position
            - background-attachment
            - background-size
            - background-clip
            - box-shadow
            - visibility
            - clip
            - clip-path
            - opacity
            - transform
            - transition
            - animate
            - cursor
    QualifyingElement:
        allow_element_with_attribute: true
        allow_element_with_class: true
    SelectorFormat:
        convention: hyphenated_BEM
    SpaceBeforeBrace:
        allow_single_line_padding: true
